#!/bin/bash
docker run -dt --name data-container -h data-container jreeme/data-container:7.0
docker run -dt --volumes-from data-container --name mongo -h mongo jreeme/mongo:7.0
docker run -dt --volumes-from data-container --name mysql -h mysql jreeme/mysql:7.0
